### PR TITLE
Use meta tags to get language code

### PR DESCRIPTION
**Pull request by mmaterowski**
Hey. I didn't found out much, but lang property is no more available on documentElement, nor on body. I used meta tags and extension is now loaded, but stuff is still not working properly

Tested on : Brave Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit)

Additional hints:
- You may use _document.body.onkeydown_ instead of addEventListener in line 87
- Send a like is now **div** not **a** node

### CODE REVIEW

**Comment by guoguo12** [comment]
Thanks! `document.documentElement.lang` shows up fine for me. Do you think it's specific to Brave? Or to non-English languages?

**Comment by mmaterowski** [comment]
image
Something's fishy here and I'm not quite sure what's the problem tbh. `document.documentElement.lang` is just a shortcut for accessing property that I can indeed see in html tag. 

I guess You may use this method as a fallback, but I think it might be even better idea to check if there's any value before fetching .json and set it to en just in case, otherwise it will crash the extension 😢 

I tested it both on chrome (87.0.4280.88 ) and brave and even if it finds the right language code it cannot fetch .json.

**Comment by mmaterowski** [comment]
Tested locally with updated master - looks good and there's no errors.
I guess You may ignore the PR.

Although alt+up/down does not seem to work. Are You planning to add this feature to new version? 

I may take a look at it if there are some problems, coz' it's the most crucial thing for me in this extension :D

**Comment by guoguo12** [comment]
Ah, I'm not planning to add it. I couldn't figure out how to determine which chat is currently selected. Let me know if you make any progress!

**Pull request closed without merging**
