### PR TITLE
Search in current conversation

### PR DESCRIPTION
**Pull request by Code-Curious**
Added `Alt+Shift+F` shortcut for searching messages in current conversation.

### CODE REVIEW

**Comment by guoguo12** [comment]
Thanks! Will review later today.

**Comment by guoguo12** [comment]
Looks good, thanks!

**Comment by guoguo12** [comment]
So actually, I tested it out just now and I couldn't get it to work. There don't seem to be any `em` tags on my page. What browser/language are you using?

**Comment by Code-Curious** [comment]
You are right, it seems that the rendered HTML has changed and the selector no longer matches the target. I am going to look into it and change the selector.
I am using Chrome 59, and Messenger is in English.

**Comment by Code-Curious** [comment]
I've fixed the selector in #12.

**Pull request merged**
